:construction: Build travis yml file.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,7 +32,7 @@ before_install:
     # the version is less the 4.8 and we need to install the image package from
     # Octave Forge (possibly for other packages as well).
     # For now, lets just always say we do need to do this.
-    - UPGRADE_GCC="false"
+    - UPGRADE_GCC="true"
     # ---------------------------------------------------------------------------
     # Add repository for octave
     - travis_retry sudo add-apt-repository -y ppa:octave/stable
@@ -100,70 +100,70 @@ install:
       echo "ADDPATH_COMMAND| $ADDPATH_COMMAND";
 
 ###############################################################################
-# before_script:
-#     - testFolder = source/tests
-#     - TEST_ARGS="'-recursive', '-verbose', '-junit_xml_file', 'testresults.xml'";
-#       if [ "$COVERAGE" = "true" ]; then
-#           TEST_ARGS+=", '-with_coverage', '-cover', '$PACKAGE_FOLDER'";
-#           TEST_ARGS+=", '-cover_exclude', ${testFolder}";
-#           TEST_ARGS+=", '-cover_xml_file', 'coverage.xml'";
-#           TEST_ARGS+=", '-cover_json_file', 'coveralls.json'";
-#       fi;
-#       TEST_COMMAND="exit(~moxunit_runtests(${testFolder}, $TEST_ARGS));";
-#       echo "TEST_COMMAND| $TEST_COMMAND";
-#     # Double-check we are still in the right directory
-#     - pwd
-#     # Check what octave packages we have installed
-#     - octave -q --eval "ver"
-#     # ---------------------------------------------------------------------------
-#     # Remove any cached results files from previous build, if present
-#     - rm -f testresults.xml;
-#       rm -f coverage.xml;
-#       rm -f .coverage;
-#       rm -f coveralls.json;
-#     # ---------------------------------------------------------------------------
-#     # Set up folders for test results on Shippable
-#     - if [ "$SHIPPABLE" = "true" ]; then
-#         rm -fr shippable;
-#         mkdir -p shippable/testresults;
-#         mkdir -p shippable/codecoverage;
-#       fi;
+before_script:
+    - testFolder = source/tests
+    - TEST_ARGS="'-recursive', '-verbose', '-junit_xml_file', 'testresults.xml'";
+      if [ "$COVERAGE" = "true" ]; then
+          TEST_ARGS+=", '-with_coverage', '-cover', '$PACKAGE_FOLDER'";
+          TEST_ARGS+=", '-cover_exclude', ${testFolder}";
+          TEST_ARGS+=", '-cover_xml_file', 'coverage.xml'";
+          TEST_ARGS+=", '-cover_json_file', 'coveralls.json'";
+      fi;
+      TEST_COMMAND="exit(~moxunit_runtests(${testFolder}, $TEST_ARGS));";
+      echo "TEST_COMMAND| $TEST_COMMAND";
+    # Double-check we are still in the right directory
+    - pwd
+    # Check what octave packages we have installed
+    - octave -q --eval "ver"
+    # ---------------------------------------------------------------------------
+    # Remove any cached results files from previous build, if present
+    - rm -f testresults.xml;
+      rm -f coverage.xml;
+      rm -f .coverage;
+      rm -f coveralls.json;
+    # ---------------------------------------------------------------------------
+    # Set up folders for test results on Shippable
+    - if [ "$SHIPPABLE" = "true" ]; then
+        rm -fr shippable;
+        mkdir -p shippable/testresults;
+        mkdir -p shippable/codecoverage;
+      fi;
   
-#   ###############################################################################
+###############################################################################
 #   script:
 #     - octave -q --eval "$ADDPATH_COMMAND $TEST_COMMAND";
   
-#   ###############################################################################
-#   after_script:
-#     # Check where we ended up and what's going on where we are
-#     - pwd
-#     - ls -alh
-#     # ---------------------------------------------------------------------------
-#     # Move results and coverage files into appropriate places
-#     - if [ "$SHIPPABLE" = "true" ] && [ -f testresults.xml ]; then
-#         mv testresults.xml shippable/testresults/;
-#       fi;
-#       if [ "$SHIPPABLE" = "true" ] && [ -f coverage.xml ]; then
-#         cp coverage.xml shippable/codecoverage/;
-#       fi;
+###############################################################################
+after_script:
+    # Check where we ended up and what's going on where we are
+    - pwd
+    - ls -alh
+    # ---------------------------------------------------------------------------
+    # Move results and coverage files into appropriate places
+    - if [ "$SHIPPABLE" = "true" ] && [ -f testresults.xml ]; then
+        mv testresults.xml shippable/testresults/;
+      fi;
+      if [ "$SHIPPABLE" = "true" ] && [ -f coverage.xml ]; then
+        cp coverage.xml shippable/codecoverage/;
+      fi;
   
-#   ###############################################################################
-#   after_success:
-#     # Only run coveralls on Travis. When running on a public Travis-CI, the
-#     # repo token is automatically inferred, but to run coveralls on Shippable
-#     # the repo token needs to be specified in a .coveralls.yml or as an
-#     # environment variable COVERALLS_REPO_TOKEN. This should be kept hidden
-#     # from public viewing, either by encrypting the token or running on a
-#     # private build.
-#     # We ignore coverage push failures because the servers are not 100%
-#     # reliable and we don't want the CI to report a failure just because the
-#     # coverage report wasn't published.
-#     # For Codecov, we use this https://github.com/codecov/codecov-bash
-#     - if [ "$COVERAGE" = "true" ] && [ "$TRAVIS" = "true" ] && [ "$SHIPPABLE" != "true" ]; then
-#         curl --verbose -F json_file=@`pwd`/coveralls.json https://coveralls.io/api/v1/jobs  || echo "Coveralls push failed";
-#         bash <(curl -s https://codecov.io/bash) || echo "Codecov push failed";
-#       fi;
+###############################################################################
+after_success:
+    # Only run coveralls on Travis. When running on a public Travis-CI, the
+    # repo token is automatically inferred, but to run coveralls on Shippable
+    # the repo token needs to be specified in a .coveralls.yml or as an
+    # environment variable COVERALLS_REPO_TOKEN. This should be kept hidden
+    # from public viewing, either by encrypting the token or running on a
+    # private build.
+    # We ignore coverage push failures because the servers are not 100%
+    # reliable and we don't want the CI to report a failure just because the
+    # coverage report wasn't published.
+    # For Codecov, we use this https://github.com/codecov/codecov-bash
+    - if [ "$COVERAGE" = "true" ] && [ "$TRAVIS" = "true" ] && [ "$SHIPPABLE" != "true" ]; then
+        curl --verbose -F json_file=@`pwd`/coveralls.json https://coveralls.io/api/v1/jobs  || echo "Coveralls push failed";
+        bash <(curl -s https://codecov.io/bash) || echo "Codecov push failed";
+      fi;
   
-#   ###############################################################################
-#   # Enable archiving of artifacts on Shippable (does nothing on Travis)
-#   archive: true      
+###############################################################################
+# Enable archiving of artifacts on Shippable (does nothing on Travis)
+archive: true      
